"""
train.py
========
Training loop for CrazyGoNet — AlphaZero-style self-play training.

Usage:
  python ml_training/train.py
  python ml_training/train.py --resume ml_training/checkpoints/latest.pt
  python ml_training/train.py --data ml_training/data/phase1 --epochs 10

Training data format: JSONL files generated by generate_games.ts
Each line: {"board_size": 9, "positions": [...], "winner": 1}
"""

import os
import sys
import json
import glob
import time
import argparse
import math
from pathlib import Path
from typing import Iterator

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Add parent directory to path so we can import model.py
sys.path.insert(0, str(Path(__file__).parent))
from model import CrazyGoNet, create_model


# ── Hyperparameters ────────────────────────────────────────────────────────────

BOARD_SIZE       = 9
BATCH_SIZE       = 512    # Fits comfortably in 16 GB VRAM with ResNet-12
LEARNING_RATE    = 2e-3
LR_MIN           = 1e-4
WEIGHT_DECAY     = 1e-4
CHECKPOINT_EVERY = 500    # steps between checkpoints
LOG_EVERY        = 50     # steps between console logs
LAMBDA_VALUE     = 1.0    # weight for value loss
LAMBDA_OWNERSHIP = 0.15   # weight for ownership loss (same as KataGo)
REPLAY_BUFFER_MAX = 500_000  # max positions in replay buffer


# ── Dataset ────────────────────────────────────────────────────────────────────

class GoReplayBuffer:
    """
    In-memory replay buffer loaded from JSONL files.
    Stores up to REPLAY_BUFFER_MAX positions with FIFO eviction.
    """

    def __init__(self, board_size: int, max_size: int = REPLAY_BUFFER_MAX):
        self.board_size = board_size
        self.max_size   = max_size
        self.tensors    : list[np.ndarray] = []  # [16, N, N]
        self.policies   : list[np.ndarray] = []  # [N*N+1]
        self.values     : list[np.ndarray] = []  # [n_players]
        self.ownerships : list[np.ndarray] = []  # [N, N]

    def load_file(self, filepath: str) -> int:
        """Load all positions from a JSONL file. Returns count added."""
        added = 0
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    game = json.loads(line)
                except json.JSONDecodeError:
                    continue

                for pos in game.get('positions', []):
                    tensor    = np.array(pos['tensor'],           dtype=np.float32)  # [16, N, N]
                    policy    = np.array(pos['policy_target'],    dtype=np.float32)  # [N*N+1]
                    value     = np.array(pos['value_target'],     dtype=np.float32)  # [2]
                    ownership = np.array(pos['ownership_target'], dtype=np.float32)  # [N, N]

                    # Validate shape
                    if tensor.shape != (16, self.board_size, self.board_size):
                        continue

                    self.tensors.append(tensor)
                    self.policies.append(policy)
                    self.values.append(value)
                    self.ownerships.append(ownership)
                    added += 1

        # FIFO eviction if buffer is full
        if len(self.tensors) > self.max_size:
            excess = len(self.tensors) - self.max_size
            self.tensors    = self.tensors[excess:]
            self.policies   = self.policies[excess:]
            self.values     = self.values[excess:]
            self.ownerships = self.ownerships[excess:]

        return added

    def load_directory(self, directory: str) -> int:
        """Load all JSONL files from a directory."""
        files = sorted(glob.glob(os.path.join(directory, '*.jsonl')))
        total = 0
        for f in files:
            n = self.load_file(f)
            total += n
            print(f'  Loaded {n:6,} positions from {os.path.basename(f)} | Buffer: {len(self.tensors):,}')
        return total

    def __len__(self):
        return len(self.tensors)

    def sample_batch(self, batch_size: int) -> dict[str, torch.Tensor]:
        """Sample a random batch from the buffer."""
        N = len(self.tensors)
        idx = np.random.randint(0, N, size=batch_size)
        return {
            'tensor':    torch.from_numpy(np.stack([self.tensors[i]    for i in idx])),
            'policy':    torch.from_numpy(np.stack([self.policies[i]   for i in idx])),
            'value':     torch.from_numpy(np.stack([self.values[i]     for i in idx])),
            'ownership': torch.from_numpy(np.stack([self.ownerships[i] for i in idx])),
        }


# ── Loss Functions ─────────────────────────────────────────────────────────────

def policy_loss(logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """Cross-entropy between MCTS/random policy and predicted policy."""
    # targets is a probability distribution, logits are raw scores
    log_probs = torch.log_softmax(logits, dim=-1)
    return -(targets * log_probs).sum(dim=-1).mean()


def value_loss(preds: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """Mean squared error between predicted and actual win probabilities."""
    return nn.functional.mse_loss(preds, targets)


def ownership_loss(preds: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """
    Binary cross-entropy between predicted ownership and ground truth.
    preds: [batch, 1, N, N] in [-1, 1] (Tanh output)
    targets: [batch, N, N]  in {-1, 0, 1}
    """
    preds_flat   = preds.squeeze(1).flatten(1)          # [batch, N*N]
    targets_flat = targets.flatten(1)                    # [batch, N*N]
    # Normalize from [-1,1] to [0,1] for BCE
    p = (preds_flat + 1) / 2
    t = (targets_flat + 1) / 2
    return nn.functional.binary_cross_entropy(p.clamp(1e-6, 1 - 1e-6), t.clamp(0, 1))


def total_loss(
    policy_logits: torch.Tensor,
    value_preds:   torch.Tensor,
    ownership_map: torch.Tensor,
    policy_tgt:    torch.Tensor,
    value_tgt:     torch.Tensor,
    ownership_tgt: torch.Tensor,
) -> tuple[torch.Tensor, dict[str, float]]:
    lp = policy_loss(policy_logits, policy_tgt)
    lv = value_loss(value_preds, value_tgt)
    lo = ownership_loss(ownership_map, ownership_tgt)

    loss = lp + LAMBDA_VALUE * lv + LAMBDA_OWNERSHIP * lo
    return loss, {
        'loss_total':     loss.item(),
        'loss_policy':    lp.item(),
        'loss_value':     lv.item(),
        'loss_ownership': lo.item(),
    }


# ── Checkpoint Utilities ───────────────────────────────────────────────────────

def save_checkpoint(model, optimizer, scheduler, step: int, checkpoint_dir: str):
    os.makedirs(checkpoint_dir, exist_ok=True)
    path = os.path.join(checkpoint_dir, f'checkpoint_step_{step:06d}.pt')
    torch.save({
        'step':                step,
        'model_state_dict':    model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict() if scheduler else None,
    }, path)
    # Also save as "latest"
    latest = os.path.join(checkpoint_dir, 'latest.pt')
    torch.save({
        'step':                step,
        'model_state_dict':    model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict() if scheduler else None,
    }, latest)
    print(f'  [Saved] {path}')


def load_checkpoint(path: str, model, optimizer=None, scheduler=None) -> int:
    print(f'Loading checkpoint: {path}')
    ckpt = torch.load(path, map_location='cpu', weights_only=True)
    saved_state = ckpt['model_state_dict']
    current_state = model.state_dict()

    matched_state = {}
    mismatched_keys = []

    for k, v in saved_state.items():
        if k in current_state:
            if v.shape == current_state[k].shape:
                matched_state[k] = v
            else:
                mismatched_keys.append(f'{k} (saved {tuple(v.shape)} vs model {tuple(current_state[k].shape)})')

    model.load_state_dict(matched_state, strict=False)

    if mismatched_keys:
        print(f'  [Transfer Learning] Transferred {len(matched_state)} layers (ResNet-12 convolutional backbone).')
        print(f'  [Transfer Learning] Re-initialized {len(mismatched_keys)} final head layers for new board dimension:')
        for mk in mismatched_keys:
            print(f'    - {mk}')
    else:
        print(f'  Loaded all {len(matched_state)} layers exactly.')
        if optimizer and 'optimizer_state_dict' in ckpt:
            try:
                optimizer.load_state_dict(ckpt['optimizer_state_dict'])
            except Exception:
                print('  [Notice] Optimizer state reset for new learning schedule.')
        if scheduler and ckpt.get('scheduler_state_dict'):
            try:
                scheduler.load_state_dict(ckpt['scheduler_state_dict'])
            except Exception:
                pass

    step = ckpt.get('step', 0)
    print(f'  Resumed from step {step}')
    return step


# ── Training Loop ──────────────────────────────────────────────────────────────

def train(args: argparse.Namespace):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'\nDevice: {device}')
    if device.type == 'cuda':
        print(f'GPU:    {torch.cuda.get_device_name(0)}')
        print(f'VRAM:   {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

    # ── Model ──────────────────────────────────────────────────────────────────
    model = create_model(board_size=args.board_size, phase=1).to(device)
    total_params = sum(p.numel() for p in model.parameters())
    print(f'Model:  CrazyGoNet ResNet-12 ({total_params / 1e6:.1f}M params)\n')

    # ── Optimizer + Scheduler ─────────────────────────────────────────────────
    optimizer = optim.Adam(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=args.max_steps,
        eta_min=LR_MIN,
    )

    # ── Resume ─────────────────────────────────────────────────────────────────
    start_step = 0
    if args.resume:
        start_step = load_checkpoint(args.resume, model, optimizer, scheduler)

    # ── Load Data ─────────────────────────────────────────────────────────────
    print(f'Loading training data from: {args.data}')
    buffer = GoReplayBuffer(board_size=args.board_size)
    total_pos = buffer.load_directory(args.data)
    print(f'\nTotal positions in buffer: {len(buffer):,}')

    if len(buffer) < BATCH_SIZE:
        print(f'\n[ERROR] Not enough training data! Have {len(buffer)} positions, need {BATCH_SIZE}.')
        print(f'        Run generate_games.ts first to generate more data.')
        sys.exit(1)

    # ── Training Loop ─────────────────────────────────────────────────────────
    print(f'\nStarting training from step {start_step + 1}...')
    print('Press Ctrl+C at any time to stop and resume later.\n')
    print(f'{"Step":>6} | {"Loss":>8} | {"Policy":>8} | {"Value":>8} | {"Ownership":>9} | {"LR":>8}')
    print('-' * 65)

    model.train()
    step = start_step
    checkpoint_dir = args.checkpoint_dir

    try:
        while step < args.max_steps:
            batch = buffer.sample_batch(BATCH_SIZE)
            tensor    = batch['tensor'].to(device)
            policy    = batch['policy'].to(device)
            value     = batch['value'].to(device)
            ownership = batch['ownership'].to(device)

            optimizer.zero_grad()
            out = model(tensor)

            loss, metrics = total_loss(
                out['policy'], out['value'], out['ownership'],
                policy, value, ownership,
            )
            loss.backward()

            # Gradient clipping for stability
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()
            scheduler.step()

            step += 1

            if step % LOG_EVERY == 0:
                lr = optimizer.param_groups[0]['lr']
                print(
                    f'{step:>6} | '
                    f'{metrics["loss_total"]:>8.4f} | '
                    f'{metrics["loss_policy"]:>8.4f} | '
                    f'{metrics["loss_value"]:>8.4f} | '
                    f'{metrics["loss_ownership"]:>9.4f} | '
                    f'{lr:>8.6f}'
                )

            if step % CHECKPOINT_EVERY == 0:
                save_checkpoint(model, optimizer, scheduler, step, checkpoint_dir)

    except KeyboardInterrupt:
        print('\n\nTraining interrupted by user.')
        save_checkpoint(model, optimizer, scheduler, step, checkpoint_dir)
        print(f'Progress saved. Resume with: python ml_training/train.py --resume {checkpoint_dir}/latest.pt')

    print(f'\nTraining complete at step {step}.')
    save_checkpoint(model, optimizer, scheduler, step, checkpoint_dir)


# ── Entry Point ────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train CrazyGoNet')
    parser.add_argument('--board-size',     default=9, type=int,
                        help='Board dimension N (default: 9)')
    parser.add_argument('--data',           default='ml_training/data/phase1',
                        help='Directory with JSONL training data')
    parser.add_argument('--resume',         default=None,
                        help='Path to checkpoint .pt file to resume from')
    parser.add_argument('--checkpoint-dir', default='ml_training/checkpoints',
                        help='Directory to save checkpoints')
    parser.add_argument('--max-steps',      default=50_000, type=int,
                        help='Maximum training steps (default: 50000)')
    args = parser.parse_args()

    train(args)
